name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AAWS__ACCESSKEYID }}
          aws-secret-access-key: ${{ secrets.AWS__SECRETACCESSKEY }}
          aws-region: ${{ secrets.AWS__REGION}}

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
            --service ${{ secrets.ECS_SERVICE_NAME }} \
            --force-new-deployment